### ISSUE TITLE
xz: (stdin): File format not recognized (when trying to install infer v1.2.0)

### ISSUE THREAD

**Issue by yegor256** [srz-zumix/setup-infer#12]
This is my CI job:

```yaml
  infer:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: srz-zumix/setup-infer@v1
        with:
          infer_version: v1.2.0
      - run: infer --version
      - run: infer run -- mvn test
```

I'm getting this (full [log](https://github.com/yegor256/xembly/actions/runs/13096105986/job/36538555829)):

```
 Installing infer ...
  xz: (stdin): File format not recognized
  tar: Child returned status 1
  tar: Error is not recoverable: exiting now
  Error: Process completed with exit code 2.
```

Works fine with infer `v1.0.0` though.
